### PR TITLE
added ability to modify the used S3 scheme in URIs

### PR DESCRIPTION
**Pull request by tobithiel**
Thanks for writing this library. It is very helpful!
I've found it to be a bit painful to work with the custom scheme that's being used when enabling fake S3. Other libraries are not always prepared to handle that. That's why I've added the ability to customize the scheme that is being used. It shouldn't break any existing usage, as the defaults are still the same.
Let me know what you think and if you'd be interested in merging this.

### CODE REVIEW

**Comment by ocadaruma** [comment]
@tobithiel Thank you for submitting PR.
In my opinion, existing `fake.awsS3Endpoint` property can work with any custom scheme. (as described in [README](https://github.com/opt-tech/redshift-fake-driver#with-fake-s3)).

How does `fake.awsS3Scheme` property differ from `fake.awsS3Endpoint` ?

**Comment by ocadaruma** [comment]
@tobithiel I understood. This PR looks good.
I will merge this then add some usage to README and release new version.

Thank you!

**Comment by tobithiel** [comment]
@ocadaruma Thank you. Let me know if I can help get to get this ready to be merged.

**Comment by ocadaruma** [comment]
@tobithiel I've released redshift-fake-driver:1.0.4 .

**Comment by tobithiel** [comment]
@ocadaruma Thank you 👍

**Pull request merged**
